### ISSUE TITLE
**OpenAI API Errors: Internal Server Error and Bad Gateway**

### ISSUE THREAD

**Issue by Nbtguyoriginal** [AntonOsika/gpt-engineer#812] opened 2023-10-20 00:34 UTC
---

### Title: 
**OpenAI API Errors: Internal Server Error and Bad Gateway**

### Issue Description:

When attempting to run `gpt-engineer` with specific projects and configurations following the steps closely, I consistently encounter OpenAI API errors, specifically "Internal Server Error" and "Bad Gateway".

#### Environment:
- OS: Windows Not docker
- Command Prompt Location: `C:\Users\path\OneDrive\Desktop\auto gen\working gen\gpt engineer\gpt-engineer`

#### Steps to Reproduce:
1. Installed `gpt-engineer` using the command: `python -m pip install gpt-engineer`. The installation completed without any issues.
2. Ran the following commands:
   - `gpt-engineer projects\gen gpt-3.5-turbo-16k-0613 -i` ~~ error received 
   - ' checked the help command for clarity the attempted to run with the default gpt4
   - `gpt-engineer projects\gen -i` ~~ error received 

Both commands resulted in the same errors.
if needed i can run the commands in the same terminal to provide both error logs

#### Expected Behavior:
The `gpt-engineer` tool should run without any errors and complete the intended operations. as per the instructions 

#### Actual Behavior:
The tool encounters OpenAI API errors and eventually and errors until a user aborts the operation. The errors observed are:
- Internal server error with error type `auth_subrequest_error` and error code `internal_error`.
- Bad gateway error with error type `cf_bad_gateway` and error code `502`.

#### Logs:
```
INFO:openai:error_code=502 error_message='Bad gateway.' error_param=None error_type=cf_bad_gateway message='OpenAI API error received' stream_error=False
...
WARNING:langchain.llms.base:Retrying langchain.chat_models.openai.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIError: Bad gateway. ...
...
Aborted!
```

#### Additional Notes:
- The file list for the improvement process was detected at `C:\Users\path\OneDrive\Desktop\auto gen\working gen\gpt engineer\gpt-engineer\projects\gen\.gpteng\file_list.txt`.
- The inserted prompt provides an overview of the OpenAI Integration & Multi-Agent Conversational Environment.

#### Recommendations:
- Please help me to investigate the root cause of these API errors id love to use this tool or at least try it .
- It would be helpful to have more descriptive error messages or suggestions for troubleshooting in the event of such errors. or potentially a chatbot traind on the code base to provide insight  

__
[gpt-engineer( potential bug inside).zip](https://github.com/AntonOsika/gpt-engineer/files/13048694/gpt-engineer.potential.bug.inside.zip)
__not sure if this is okay but some repos allow for this so here is the full directory for trouble shooting__
ty in advance for any help 
---

I've attempted to disable cloud flare and restart only to receive the same error any help would be appreciated

**Comment by ATheorell** [comment] 2023-10-20 09:03
Are you providing an OPENAI_API_KEY in the environment variable with the same name? auth_subrequest_error sounds like it.

If this is not the cause of the error, please provide a full stack trace

**Comment by ATheorell** [comment] 2023-10-21 18:06
Im pretty sure that the problem is that you haven't set OPENAI_API_KEY in your environment. Closing

**Closed by ATheorell** 2023-10-21 18:06 UTC
Labels: bug, triage
