### ISSUE TITLE
"No API key provided" - altough it is provided in the .env file

### ISSUE THREAD

**Issue by LeRobert** [AntonOsika/gpt-engineer#589] opened 2023-08-14 09:40 UTC
## Expected Behavior

If the OpenAI API key is provided in the .env file, it should be recognized and used.

## Current Behavior

Runtime error message: openai.error.AuthenticationError: No API key provided.

### Steps to Reproduce

1. Set the key in the .env file
2. Run the app with gpt-engineer projects/my-new-project

### Solution

When I added the line `openai.api_key = os.getenv("OPENAI_API_KEY")` to the end of the function `load_env_if_needed()` in the file `main.py`, as well as `import openai` at the beginning of this file _(thanks, engerlina, for reminder)_, the issue was resolved.

**Comment by engerlina** [comment] 2023-08-14 13:21
You also need to import openai in the main.py file

**Comment by LeRobert** [comment] 2023-08-14 14:53
> What is the proper place for the .env file?

It works fine if it's in the gpt-engineer's root (same place as .env.template).

**Comment by redocdm** [comment] 2023-08-15 01:07
does this method only work cloning git versus installing it with pip?

**Comment by pbharrin** [comment] 2023-08-15 05:07
This method (creating a .env file) should work for either installing with pip or cloning with git.  It would be easier to set the env variable if you installed with pip as you don't have to figure out where to place the .env file.  

I'm going to close this issue as the fix has been merged.

**Closed by pbharrin** 2023-08-15 05:07 UTC

**Comment by AntonOsika** [comment] 2023-08-16 19:30
I'm a bit confused as of why the PR was necessary.

Is it working better since the fix @LeRobert? Shouldn't having the key as env variable be enough?

If you can explain why importing openai is necessary @engerlina @pbharrin would be great

**Comment by pbharrin** [comment] 2023-08-16 21:54
I had this same question.  

[The line that is called to set the OpenAI API key](https://github.com/AntonOsika/gpt-engineer/blob/main/gpt_engineer/main.py#L23C5-L23C11) is: 
`openai.api_key = os.getenv("OPENAI_API_KEY")`.  

In order to globally set the OpenAI instance variable `api_key` we first need to have access to the OpenAI singleton.   That is why we need the import statement.

**Comment by engerlina** [comment] 2023-08-17 02:30
All I know is that I ran into the same issue: Runtime error message: openai.error.AuthenticationError: No API key provided.

And when I updated the code as @LeRobert proposed it worked (except that of course you need to import it).

So once you do both, the code works as expected.

So apologies, if I didn't solve the root cause and I don't know why even with the .env file updated and in the right folders it didn't work before.

**Comment by LeRobert** [comment] 2023-08-17 09:25
> I'm a bit confused as of why the PR was necessary.
> 
> Is it working better since the fix @LeRobert? Shouldn't having the key as env variable be enough?

Yes, it works correctly now. The API key can be provided via the env variable in the OS or via the .env file in the root. For both cases, the line was missing to provide this key further to the openai object. And to use this object, the import is required.
